ALTER TABLE CLIENTES ADD FONE_1_DDD VARCHAR (2);
ALTER TABLE CLIENTES ADD FONE_1_PARTE_1 VARCHAR (5);
ALTER TABLE CLIENTES ADD FONE_1_PARTE_2 VARCHAR (5);

ALTER TABLE CLIENTES ADD FONE_2_DDD VARCHAR (2);
ALTER TABLE CLIENTES ADD FONE_2_PARTE_1 VARCHAR (5);
ALTER TABLE CLIENTES ADD FONE_2_PARTE_2 VARCHAR (5);
